name: jarvis
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  assets_audio_player: ^2.0.13+1
  speech_to_text: ^3.0.1
  permission_handler: ^5.0.1+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/tracks/intro.mp3
  fonts:
    - family: StarkIndustries
      fonts:
        - asset: assets/fonts/Stark-6p31.ttf
        - asset: assets/fonts/StarkBold-y4zV.ttf
        - asset: assets/fonts/StarkItalic-1zWv.ttf
          style: italic